# workaround for https://github.com/rust-lang/cargo/issues/6745
[workspace]

[package]
edition = "2021"
name = "sidevm-timer"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
once_cell = "1.10.0"
pink-sidevm-env = {path = "../../sidevm/env"}
tokio = {version = "1", features = ["macros"]}
