[package]
edition = "2021"
name = "pink-sidevm-runtime"
version = "0.1.0"

[dependencies]
anyhow = "1.0"
log = "0.4.16"
loupe = "0.1.3"
pink-sidevm-env = {path = "../env", features = ["runtime"]}
tokio = {version = "1.17.0", features = ["full"]}
wasmer = "2.2.1"
wasmer-compiler-singlepass = "2.2.1"
wasmer-engine = "2.2.1"
wasmer-engine-universal = "2.2.1"
wasmer-tunables = {path = "../../../wasmer-tunables"}
