[package]
edition = "2021"
name = "pink-sidevm-env"
version = "0.1.0"

[dependencies]
pink-sidevm-macro = {path = "../macro"}

scale = {package = "parity-scale-codec", version = "3", default-features = false, features = ["derive"]}
tinyvec = {version = "1.5.1", features = ["alloc"]}

[dev-dependencies]
once_cell = "1.10.0"