name: Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  e2e-test:
    name: Run E2E tests
    runs-on: ubuntu-20.04
    steps:
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2021-11-11
          override: true
          target: wasm32-unknown-unknown
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: ./.github/actions/install_toolchain
      - name: Install gramine
        run: sudo bash dockerfile.d/01_apt_gramine.sh
      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Install yarn 2
        run: sudo npm install -g yarn && yarn set version berry
      - name: mkdir
        run: mkdir -p ./target/release
      - name: Download phala-node
        run: curl https://files.kvin.wang:8443/phala-node -o ./target/release/phala-node
      - name: Download pherry
        run: curl https://files.kvin.wang:8443/pherry -o ./target/release/pherry
      - name: Download pruntime
        run: curl https://files.kvin.wang:8443/pruntime -o ./standalone/pruntime/bin/pruntime
      - name: Download pruntime.manifest
        run: curl https://files.kvin.wang:8443/pruntime.manifest -o ./standalone/pruntime/bin/pruntime.manifest
      - name: Change permission
        run: chmod +x ./target/release/phala-node ./target/release/pherry ./standalone/pruntime/bin/pruntime
      - name: Run E2E tests
        run: yarn set version berry && cd ./e2e/ && YARN_ENABLE_IMMUTABLE_INSTALLS=false yarn && yarn test || ll phala-e2e-*/** && cat phala-e2e-*/*.log

