name: Build and Test (Teaclave)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  e2e-test:
    name: Run E2E tests
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: Run E2E tests
        id: e2e
        run: echo "/opt/intel/sgxsdk/lib64/" | sudo tee /etc/ld.so.conf.d/intel-libsgx.conf | sudo ldconfig && source /opt/intel/sgxsdk/environment && cd ./standalone/pruntime/bin/ && ./app -c 0

      - name: Pack logs if fail
        id: packlogs
        if: always()
        run: |
          if [[ ${{ steps.e2e.outcome }} == failure ]]; then
            tar czvf e2e-logs.tar.gz e2e
          fi
      - name: Upload logs if fail
        #if: ${{ steps.packlogs.outcome == "success" }}
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: e2e-logs
          path: e2e-logs.tar.gz

