name: Build and Test (Teaclave)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  e2e-test:
    name: Run E2E tests
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: ./.github/actions/install_toolchain
      - name: Download node
        run: wget https://files.kvin.wang:8443/core-blockchain-binaries.zip && mkdir -p target/release && unzip -o core-blockchain-binaries.zip -d target/release/
      - name: Download pruntime
        run: wget https://files.kvin.wang:8443/pruntime-binaries.zip && mkdir -p ./standalone/pruntime/bin/ && unzip -o pruntime-binaries.zip -d ./standalone/pruntime/bin/
      - name: Change permission
        run: chmod +x ./target/release/phala-node ./target/release/pherry ./standalone/pruntime/bin/app
      - name: Run E2E tests
        run: echo "/opt/intel/sgxsdk/lib64/" | sudo tee /etc/ld.so.conf.d/intel-libsgx.conf | sudo ldconfig && source /opt/intel/sgxsdk/environment && cd ./standalone/pruntime/bin/ && ./app -c 0

